### ISSUE TITLE
How to put the camera view under the kivy view?

### ISSUE THREAD

**Issue by yihuang** [tito/android-zbar-qrcode#1]
Because i want to draw something on camera view.
I've tried this, but didn't work:

```
          activity = PythonActivity.mActivity
          activity.addContentView(view, LayoutParams(*self.size))
          view.setZOrderOnTop(True)
          view.setX(self.x)
          view.setY(self._window.height - self.y - self.height)

          parent = cast('android.view.ViewGroup', view.getParent())
          parent.bringChildToFront(parent.getChildAt(0))

```

**Comment by yihuang** [comment]
I've tried to put both `SDLSurfaceView` and `Preview` in  a `FrameLayout`, and put `Preview` under `SDLSurfaceView`, but camera preview don't show up, maybe because `SDLSurfaceView` has a black background.

**Comment by tito** [comment]
Yes, you need to put it behind the kivy view, and force the transparency. That's how i did for the kivy-gmaps demo: https://github.com/tito/kivy-gmaps/blob/master/gmaps/__init__.py#L254
